# fly.toml app configuration file generated for mini-message-board-top13 on 2023-09-08T20:48:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-message-board-top13"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
